export const ActionType = {
    ADD_POST: 'ADD-POST',
    UPDATE_MSG: 'UPDATE-MSG',
    SET_USERS: 'SET-USERS',
    FOLLOW_TOGGLE: 'FOLLOW-TOGGLE',
    UNFOLLOW_TOGGLE: 'UNFOLLOW-TOGGLE',
    SET_USERS_COUNT: 'SET-USERS-COUNT',
    SET_CURRENT_PAGE: 'SET-CURRENT-PAGE',
    IS_LOADING_TOGGLE: 'IS-LOADING-TOGGLE',
    SET_PROFILE: 'SET-PROFILE',
    SET_USER_STATUS: 'SET_USER_STATUS',
    SET_AUTH_DATE: 'SET-AUTH-DATE',
    SET_FOLLOWING_PROGRESS: 'SET-FOLLOWING-PROGRESS',
    INITIALIZED_PROGRESS: 'INITIALIZED-PROGRESS',
    SET_AVATAR: 'SET-AVATAR',
    SET_CAPTCHA: 'SET-CAPTCHA'
};